// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jonovuoyxyzcqmpsqzdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impvbm92dW95eHl6Y3FtcHNxemRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNjA1NDQsImV4cCI6MjA2OTYzNjU0NH0.c5usZAG6fDSRZjsSUkYQcS18bI21SeBJwVnWR1xO69Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);